import { GoogleGenAI } from "@google/genai";
import { StockStyle } from "../types";

const apiKey = process.env.API_KEY || '';

// Initialize the client
const ai = new GoogleGenAI({ apiKey });

const STYLE_PROMPTS: Record<StockStyle, string> = {
  standard: "Ensure balanced, neutral professional lighting and high clarity.",
  vibrant_product: "Apply commercial product photography styling: vibrant colors, high contrast, sharp focus, and clean lighting.",
  soft_portrait: "Apply portrait photography styling: soft diffused lighting, flattering skin tones, and a shallow depth of field (bokeh).",
  architectural: "Apply architectural photography styling: perfect perspective correction, straight vertical lines, cool neutral white balance, and high dynamic range.",
  cinematic: "Apply cinematic styling: dramatic lighting, color grading with teal and orange undertones, and a filmic look."
};

export const generateEditedImage = async (
  base64Image: string, 
  mimeType: string, 
  userPrompt: string,
  style: StockStyle,
  maskReferenceBase64?: string | null
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing.");
  }

  try {
    const model = 'gemini-2.5-flash-image';
    
    // Construct the prompt
    let instructions = `Transform this image into a high-end professional stock photo. `;
    
    // 1. Style instructions
    instructions += STYLE_PROMPTS[style] || STYLE_PROMPTS.standard;
    
    // 2. User specific prompt
    if (userPrompt) {
      instructions += ` Specific instructions: ${userPrompt}.`;
    }

    // 3. Mask removal instructions
    if (maskReferenceBase64) {
      instructions += ` IMPORTANT: The second image provided is a reference mask. Remove the object that is highlighted in RED in the second image from the first image. Fill in the background naturally and seamlessly.`;
    }

    instructions += " Ensure the final output is free of artifacts and looks like a native high-resolution photograph.";

    const parts: any[] = [
      {
        inlineData: {
          data: base64Image,
          mimeType: mimeType,
        },
      }
    ];

    // If we have a mask reference, add it as the second image
    if (maskReferenceBase64) {
      parts.push({
        inlineData: {
          data: maskReferenceBase64,
          mimeType: "image/png", // Canvas export is usually PNG
        },
      });
    }

    // Add the text prompt last
    parts.push({ text: instructions });

    const response = await ai.models.generateContent({
      model,
      contents: { parts },
    });

    // Parse the response to find the generated image
    if (response.candidates && response.candidates.length > 0) {
      const content = response.candidates[0].content;
      if (content && content.parts) {
        for (const part of content.parts) {
          if (part.inlineData && part.inlineData.data) {
            return part.inlineData.data;
          }
        }
      }
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Error generating image:", error);
    throw error;
  }
};
